spring.application.name=UniSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/unidb
spring.datasource.username=postgres
spring.datasource.password=Aleff123.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true